<a href="https://colab.research.google.com/github/joseluisech/Precios_y_ventas/blob/main/Precios_y_Ventas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Lista de Precios
# El precio de venta de 3 artículos en la venta de pasteles es: $2 por un brownie, $1 por una galleta y $10 por un pastel.
# Asignen estos valores a una lista denominada price (precio).

price = [2, 1, 10]
type(price)




list

In [2]:
# Lista de Cantidad
# El club vende 17 brownies, 40 galletas y un pastel.
# Asignen estos valores a una lista denominada quantity_sold (cantidades vendidas).

quantity_sold = [17, 40, 1]
type(quantity_sold)


list

In [3]:
# No podemos realizar cálculos entre las listas

# Ahora debemos encontrar el dinero recaudado para cada tipo de elemento.  Queremos el precio * cantidad para cada elemento.
# Tratemos de multiplicar nuestras listas:

import numpy as np

price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)



numpy.ndarray

In [4]:
#¡Sí! Al usar los arrays de NumPy podemos determinar fácilmente que recaudamos
#$34 de la venta de brownies, $40 de la venta de galletas y $10 de la venta de pasteles.


price_array * quantity_sold_array


array([34, 40, 10])

In [5]:
#  Primero, creen un array de NumPy que corresponda al costo de fabricación de cada uno de los artículos vendidos en la venta de pasteles.
# Digamos que cuesta $0,25 para hacer un brownie, una galleta, $0,50 y un pastel, $5,00.

cost_array = np.array([0.25, 0.50, 5.00])


In [6]:
# Para encontrar la ganancia de cada artículo, queremos restar el costo del precio.
# Una matriz NumPy realizará la resta por elementos como se muestra:

profit_array = price_array - cost_array
print(profit_array)


[1.75 0.5  5.  ]


In [7]:
# Supongamos que quieren identificar qué elementos obtuvieron un beneficio superior a $2 por elemento.
# Pueden usar el siguiente código para preguntar si la declaración es True (verdadera) o False (falsa) para cada elemento en el array.

profit_array > 2.00


array([False, False,  True])

In [8]:
# El club también vende tartas por $7, así que debemos actualizar nuestro price_array
price_array = price_array + [7]
print(price_array)


[ 9  8 17]


In [9]:
#Para regresar a los valores originales, restaremos 7, luego usaremos la función np.append() para incluir el valor 7 como se desee
# Just fixing the mistake
price_array = price_array - [7]
# The proper way to append an element to an array
price_array = np.append(price_array, 7)
print(price_array)


[ 2  1 10  7]


In [10]:
# Por ejemplo, el club quiere agregar los siguientes precios:
# $4,50 por dulces, $3 por una magdalena, $4 por una barra de pan de plátano y $9 por una torta
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)



[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [11]:
# Para comprobar el tipo de datos de los elementos del array, pueden utilizar lo siguiente:
print(price_array.dtype)


float64


In [12]:
# Eliminar
# Resulta que nadie planea hacer una torta, así que quieren eliminar el precio de ese elemento del array.
price_array = np.delete(price_array, -1)
print(price_array)


[ 2.   1.  10.   7.   4.5  3.   4. ]


In [13]:
# Reemplazar
# Después el club decide subir el precio de los pasteles de $10 a $12.
# Nuevamente, tendremos que identificar el elemento usando el índice.  Los pasteles están en el índice 2.

price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


In [14]:
# 2) Actualicen el quantity_sold_array para incluir la venta de 2 tartas, 3 bandejas de dulces, 16 magdalenas y 5 panes de plátano.
# También se darán cuenta que una de las galletas que pensaron que se había vendido en realidad se cayó al suelo, así que editen quantity_sold_array de 40 a 39.

quantity_sold_array = np.append(quantity_sold_array, [2, 3, 16, 5])
print(quantity_sold_array)

[17 40  1  2  3 16  5]


In [15]:
quantity_sold_array[1] = 39
print(quantity_sold_array)

[17 39  1  2  3 16  5]


In [16]:
# 3) Determinen la cantidad de dinero recaudado de la venta de cada elemento en la venta de la panadería.

quantity_sold_array*price_array

array([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])

In [25]:
ventas_inicial = sum(quantity_sold_array*price_array)

print("Ventas Inicial", ventas_inicial)

Ventas Inicial 180.5


In [18]:
#4) Creen un array de NumPy "quantity_leftover" que incluya la cantidad de cada elemento restante al final de la venta:
#2 pasteles, 1 tarta, 6 bandejas de dulces, 2 panes de plátano.  (brownies, galletas, pastel, tartas, bandejas de dulces, magdalenas y panes de plátano )
#Pista: Asegúrense de incluir “0” de cada elemento que se haya vendido. ¿Por qué esto es importante cuando se crea un array? Para respetar la matriz de ventas con cada tipo.

quantity_leftover = [0, 0, 2, 1, 6, 0, 2]
type(quantity_sold)


list

In [19]:
quantity_leftover = np.array(quantity_leftover)
type(quantity_leftover)


numpy.ndarray

In [23]:
# 5) El club decide vender los elementos restantes a mitad de precio, y todo se venda rápidamente.
# Determinen cuanto dinero se recaudó de la venta de liquidación.

venta_restante = sum(price_array*quantity_leftover*0.5)
print("Venta Restante", venta_restante)


Venta Restante 33.0


In [26]:
#6) ¿Cuánto dinero total se recaudó de la venta de panadería (incluido la venta del precio total y los elementos liquidados)?

venta_total = ventas_inicial+venta_restante
print("Venta Total", venta_total)

Venta Total 213.5
